from __future__ import annotations

"""Offline English retail canonical product-intent vocabulary coverage.

Clean canonical terms only — no typo probes, no provider or commercial fields.
Merged into the offline canonical registry by ``canonical_registry``.
"""

_SCHEMA_VERSION = "1.0.0"
_SOURCE = "offline_canonical_vocabulary_coverage"
_SOURCE_FILE = "canonical_vocabulary_coverage.py"
_SOURCE_PATH = "src/picwise_search_memory/canonical_vocabulary_coverage.py"
_LANGUAGE = "english"
_STATUS = "offline_source_only"

# At least 30 clean product-intent terms per retail mega category (18 categories).
_COVERAGE_BY_MEGA_CATEGORY: dict[str, tuple[str, ...]] = {
    "home_appliances_laundry_climate": (
        "vacuum cleaner",
        "washing machine",
        "tumble dryer",
        "air conditioner",
        "dehumidifier",
        "chest freezer",
        "heat pump unit",
        "radiator heater",
        "dishwasher",
        "laundry basket",
        "clothes iron",
        "steam iron",
        "upright vacuum",
        "robot vacuum",
        "washer dryer combo",
        "front load washer",
        "top load washer",
        "portable air conditioner",
        "tower fan",
        "ceiling fan",
        "electric heater",
        "oil filled radiator",
        "air purifier",
        "humidifier",
        "window air conditioner",
        "portable dehumidifier",
        "laundry drying rack",
        "garment steamer",
        "lint remover",
        "clothes drying rack",
    ),
    "kitchen_cooking_household": (
        "coffee grinder",
        "air fryer",
        "electric kettle",
        "toaster oven",
        "rice cooker",
        "food processor",
        "cutting board",
        "frying pan",
        "kitchen knife set",
        "dish rack",
        "spice grinder",
        "mixing bowl set",
        "pressure cooker",
        "blender jar",
        "immersion blender",
        "microwave oven",
        "countertop oven",
        "stand mixer",
        "hand mixer",
        "slow cooker",
        "induction cooktop",
        "chef knife",
        "paring knife",
        "kitchen scissors",
        "measuring cups",
        "measuring spoons",
        "baking tray",
        "nonstick saucepan",
        "stock pot",
        "food storage containers",
        "glass meal prep containers",
    ),
    "furniture_living_storage_smart_home": (
        "office chair",
        "storage cabinet",
        "bookshelf unit",
        "sofa bed",
        "dining table",
        "wardrobe closet",
        "mattress topper",
        "smart thermostat",
        "motion sensor light",
        "storage ottoman",
        "desk lamp",
        "curtain rod",
        "wall shelf bracket",
        "tv stand",
        "coffee table",
        "bed frame",
        "nightstand",
        "shoe cabinet",
        "entryway bench",
        "drawer organizer",
        "underbed storage box",
        "storage bins",
        "folding table",
        "folding chair",
        "recliner chair",
        "side table",
        "bookcase",
        "smart plug",
        "smart light switch",
        "smart door sensor",
        "smart home hub",
        "floor lamp",
    ),
    "phones_mobile_accessories": (
        "usb cable",
        "phone case",
        "screen protector",
        "wireless charger",
        "power bank",
        "car mount holder",
        "sim card adapter",
        "phone stand",
        "mobile gimbal",
        "tempered glass protector",
        "earbud tips pack",
        "laptop charger",
        "usb c charger",
        "lightning cable",
        "wireless charging pad",
        "magnetic phone mount",
        "car phone holder",
        "sim eject tool",
        "portable phone tripod",
        "selfie stick",
        "camera lens protector",
        "phone ring holder",
        "charging dock",
        "dual usb car charger",
        "usb c to usb a cable",
        "fast charging adapter",
        "mobile game controller",
        "phone armband",
        "privacy screen protector",
        "tablet stylus pen",
    ),
    "computers_office_peripherals": (
        "gaming mouse",
        "mechanical keyboard",
        "usb hub",
        "monitor arm",
        "laptop stand",
        "webcam cover",
        "ethernet adapter",
        "graphics tablet",
        "ergonomic chair mat",
        "docking station",
        "external hard drive enclosure",
        "laptop sleeve",
        "laptop backpack",
        "laptop cooling pad",
        "wired mouse",
        "wireless keyboard",
        "mouse pad",
        "desk mat",
        "usb c dock",
        "displayport cable",
        "hdmi adapter",
        "laptop charger adapter",
        "usb flash drive",
        "external ssd enclosure",
        "surge protector",
        "desk organizer",
        "printer ink cartridge",
        "laser printer toner",
        "document scanner",
        "ergonomic keyboard wrist rest",
    ),
    "audio_video_gaming_cameras": (
        "bluetooth speaker",
        "wireless headphones",
        "noise cancelling headphones",
        "gaming headset",
        "soundbar subwoofer",
        "action camera",
        "mirrorless camera lens",
        "hdmi cable",
        "microphone arm",
        "portable projector",
        "turntable needle",
        "streaming capture card",
        "gaming console controller",
        "webcam microphone",
        "camera tripod",
        "camera memory card",
        "camera battery charger",
        "studio lights kit",
        "video capture device",
        "wireless microphone",
        "podcast microphone",
        "headphone stand",
        "speaker stands",
        "av receiver",
        "blu ray player",
        "streaming media player",
        "vr headset",
        "gaming monitor",
        "camera lens filter",
        "portable audio recorder",
        "dslr camera bag",
    ),
    "car_parts_service_maintenance": (
        "car battery",
        "brake pads",
        "brake pads set",
        "engine oil filter",
        "windshield wipers",
        "spark plugs kit",
        "cabin air filter",
        "headlight bulb",
        "coolant antifreeze",
        "serpentine belt",
        "oil drain pan",
        "jack stand pair",
        "air filter",
        "fuel filter",
        "brake fluid",
        "engine coolant",
        "timing belt",
        "alternator",
        "starter motor",
        "radiator hose",
        "thermostat housing",
        "wheel bearing",
        "engine mount",
        "transmission fluid",
        "car fuse kit",
        "headlight assembly",
        "taillight bulb",
        "wiper motor",
        "oxygen sensor",
        "battery terminal clamp",
        "car diagnostic scanner",
    ),
    "tyres_wheels_car_accessories": (
        "car tyre",
        "tyre 195 65 r15",
        "summer tyres set",
        "winter tyres set",
        "alloy wheels",
        "wheel nuts kit",
        "tyre pressure gauge",
        "car floor mats",
        "roof cargo box",
        "seat covers set",
        "jump starter pack",
        "tyre repair kit",
        "wheel alignment tool",
        "all season tyres",
        "spare wheel",
        "wheel cover set",
        "valve caps",
        "wheel balancing weights",
        "tyre inflator",
        "car air compressor",
        "wheel spacers",
        "hub centric rings",
        "car trunk organizer",
        "dash camera mount",
        "car seat cushion",
        "sunshade windshield",
        "boot liner",
        "steering wheel cover",
        "car vacuum",
        "car cleaning kit",
        "car phone charger",
        "roof rack cross bars",
    ),
    "moto_bicycle_mobility_gear": (
        "bike helmet",
        "motorbike gloves",
        "cycling gloves",
        "bicycle pump",
        "bike lock chain",
        "scooter helmet",
        "motorcycle jacket",
        "bicycle lights set",
        "pedal wrench tool",
        "cycling jersey",
        "bike rack carrier",
        "kick scooter deck",
        "bicycle chain lock",
        "bicycle water bottle",
        "bike saddle",
        "bike handlebar grips",
        "bike repair stand",
        "bicycle inner tube",
        "bike tire lever",
        "cycling shorts",
        "cycling sunglasses",
        "motorcycle helmet",
        "motorcycle boots",
        "motorcycle rain suit",
        "motorcycle tank bag",
        "scooter brake pads",
        "electric scooter charger",
        "bike pannier bag",
        "bicycle multitool",
        "bike bell",
        "knee guards",
    ),
    "power_tools_workshop": (
        "cordless drill",
        "hammer drill",
        "circular saw",
        "impact driver",
        "angle grinder",
        "bench grinder",
        "workbench vice",
        "orbital sander",
        "jigsaw blades pack",
        "tool storage cabinet",
        "dust extractor",
        "router bit set",
        "rotary tool",
        "demolition hammer",
        "reciprocating saw",
        "table saw",
        "mitre saw",
        "laser level",
        "heat gun",
        "power planer",
        "cordless screwdriver",
        "drill bit set",
        "impact sockets set",
        "nail gun",
        "staple gun",
        "air compressor",
        "air hose reel",
        "shop vacuum",
        "work light",
        "tool chest",
        "battery charger for drill",
    ),
    "hand_tools_consumables_measuring": (
        "screwdriver set",
        "digital caliper",
        "claw hammer",
        "tape measure",
        "spirit level",
        "adjustable wrench",
        "pliers set",
        "sandpaper sheets",
        "wall anchors pack",
        "safety goggles",
        "utility knife",
        "hex key set",
        "ratchet set",
        "socket set",
        "needle nose pliers",
        "locking pliers",
        "combination spanner set",
        "chisels set",
        "metal file set",
        "torx screwdriver set",
        "allen keys",
        "wire stripper",
        "measuring square",
        "contour gauge",
        "feeler gauge",
        "thread seal tape",
        "drill anchors",
        "wood screws pack",
        "nuts and bolts kit",
        "abrasive discs",
        "cutting wheels",
    ),
    "garden_outdoor_repair_building": (
        "lawn mower",
        "garden hose",
        "garden shears",
        "pruning shears",
        "leaf blower",
        "patio furniture set",
        "outdoor grill",
        "pressure washer",
        "wheelbarrow",
        "fence panels",
        "plant pots set",
        "garden trowel",
        "garden rake",
        "garden shovel",
        "hose reel",
        "watering can",
        "hedge trimmer",
        "chainsaw",
        "weed trimmer",
        "outdoor extension cord",
        "work gloves",
        "paint roller set",
        "paint brush set",
        "tile cutter",
        "cement mixer",
        "ladder",
        "scaffolding platform",
        "drain auger",
        "outdoor flood light",
        "deck screws",
        "brick trowel",
    ),
    "health_wellness_safety_devices": (
        "blood pressure monitor",
        "pulse oximeter",
        "digital thermometer",
        "first aid kit",
        "knee support brace",
        "massage gun",
        "bedroom humidifier",
        "air purifier filter",
        "walking stick",
        "hearing aid batteries",
        "compression socks pair",
        "glucose meter",
        "nebulizer machine",
        "tens unit",
        "back support belt",
        "ankle brace",
        "wrist brace",
        "hot water bottle",
        "heating pad",
        "cold pack",
        "pill organizer",
        "medication dispenser",
        "bathroom safety rail",
        "shower chair",
        "fall detection alarm",
        "safety helmet",
        "safety mask",
        "respirator mask",
        "ear protection muffs",
        "medical alert bracelet",
    ),
    "beauty_grooming_personal_care": (
        "electric toothbrush",
        "hair dryer",
        "beard trimmer",
        "face moisturizer",
        "shampoo bottle",
        "nail clipper set",
        "makeup mirror",
        "sunscreen lotion",
        "hair straightener",
        "body wash",
        "facial cleansing brush",
        "face trimmer",
        "electric shaver",
        "hair clipper",
        "epilator",
        "nail trimmer",
        "hair curler",
        "hair serum",
        "conditioner bottle",
        "facial toner",
        "cleansing foam",
        "lip balm",
        "body lotion",
        "hand cream",
        "makeup brush set",
        "beauty sponge",
        "makeup organizer",
        "bath sponge",
        "razor blades",
        "shaving foam",
    ),
    "baby_kids_pets_sports_outdoor": (
        "baby car seat",
        "stroller pushchair",
        "baby monitor",
        "pet food bowl",
        "dog leash harness",
        "dog leash",
        "football ball",
        "camping tent",
        "hiking backpack",
        "kids scooter",
        "yoga mat",
        "tennis racket",
        "baby bottle warmer",
        "baby feeding chair",
        "diaper bag",
        "baby carrier",
        "crib mattress",
        "baby safety gate",
        "pet carrier",
        "cat litter box",
        "dog bed",
        "pet grooming brush",
        "basketball hoop",
        "swimming goggles",
        "sleeping bag",
        "camping stove",
        "picnic cooler",
        "trekking poles",
        "exercise resistance bands",
        "dumbbell set",
        "soccer shin guards",
    ),
    "clothing_apparel_workwear": (
        "winter jacket",
        "rain coat",
        "denim jeans",
        "cotton t shirt",
        "hooded sweatshirt",
        "work safety vest",
        "thermal underwear set",
        "dress shirt",
        "running shorts",
        "wool sweater",
        "cargo work pants",
        "workwear trousers",
        "polo shirt",
        "linen shirt",
        "fleece jacket",
        "puffer jacket",
        "base layer top",
        "base layer leggings",
        "high visibility jacket",
        "reflective work jacket",
        "coveralls",
        "work apron",
        "softshell jacket",
        "hoodie",
        "sweatpants",
        "work gloves apparel",
        "waterproof overtrousers",
        "ski jacket",
        "thermal socks",
        "cotton hoodie",
    ),
    "footwear_shoes_sneakers_boots": (
        "running shoes",
        "running sneakers",
        "hiking boots",
        "leather dress shoes",
        "sandals flip flops",
        "walking shoes",
        "steel toe boots",
        "kids school shoes",
        "slip on loafers",
        "waterproof wellies",
        "sports cleats",
        "trail running shoes",
        "work boots",
        "ankle boots",
        "chelsea boots",
        "basketball shoes",
        "football boots",
        "tennis shoes",
        "training shoes",
        "casual sneakers",
        "canvas shoes",
        "winter boots",
        "snow boots",
        "slippers",
        "house slippers",
        "running spikes",
        "hiking sandals",
        "water shoes",
        "safety shoes",
        "non slip shoes",
        "walking sandals",
    ),
    "jewelry_watches_bags_fashion_accessories": (
        "wrist watch",
        "handbag",
        "leather belt",
        "sunglasses case",
        "crossbody bag",
        "travel backpack",
        "pearl earrings",
        "silver necklace",
        "wallet card holder",
        "wool scarf",
        "baseball cap",
        "watch strap band",
        "shoulder bag",
        "tote bag",
        "duffel bag",
        "laptop messenger bag",
        "clutch bag",
        "ring set",
        "gold bracelet",
        "silver bracelet",
        "stud earrings",
        "hoop earrings",
        "pendant necklace",
        "anklet",
        "brooch pin",
        "fashion hat",
        "bucket hat",
        "beanie hat",
        "travel wallet",
        "passport holder",
        "watch box",
    ),
}

_REQUIRED_ANCHOR_TERMS: tuple[tuple[str, str], ...] = (
    ("coffee grinder", "kitchen_cooking_household"),
    ("vacuum cleaner", "home_appliances_laundry_climate"),
    ("bluetooth speaker", "audio_video_gaming_cameras"),
    ("gaming mouse", "computers_office_peripherals"),
    ("car battery", "car_parts_service_maintenance"),
    ("bike helmet", "moto_bicycle_mobility_gear"),
    ("winter jacket", "clothing_apparel_workwear"),
    ("baby car seat", "baby_kids_pets_sports_outdoor"),
    ("usb cable", "phones_mobile_accessories"),
)


def coverage_metadata() -> dict[str, str]:
    return {
        "source": _SOURCE,
        "source_file": _SOURCE_FILE,
        "source_path": _SOURCE_PATH,
        "language": _LANGUAGE,
        "status": _STATUS,
        "schema_version": _SCHEMA_VERSION,
    }


def load_offline_canonical_coverage_by_mega_category() -> dict[str, set[str]]:
    vocab: dict[str, set[str]] = {}
    for mega_category_id in sorted(_COVERAGE_BY_MEGA_CATEGORY.keys()):
        terms = _COVERAGE_BY_MEGA_CATEGORY[mega_category_id]
        bucket = vocab.setdefault(mega_category_id, set())
        for term in terms:
            normalized = " ".join(term.split()).strip().lower()
            if not normalized:
                continue
            bucket.add(normalized)
    return vocab


def required_anchor_terms() -> tuple[tuple[str, str], ...]:
    return _REQUIRED_ANCHOR_TERMS
