from __future__ import annotations

import json
from collections import Counter
from copy import deepcopy

from .engine_registry import get_engine_registry
from .mega_category_registry import get_mega_category_registry

_ALLOWED_COVERAGE_STATUSES = {
    "architecture_locked",
    "needs_deep_expansion",
    "partially_seeded",
    "not_started",
}
_REQUIRED_LIST_FIELDS = (
    "department_seed_examples",
    "subcategory_seed_examples",
    "product_family_seed_examples",
    "spec_schema_seed_examples",
    "buying_priority_seed_examples",
    "alias_seed_examples",
    "greeklish_seed_examples",
    "typo_seed_examples",
    "intent_pattern_seed_examples",
    "ambiguity_risks",
    "safety_notes",
    "future_expansion_notes",
)
_FORBIDDEN_KEY_TOKENS = ("offer", "price", "affiliate")

_MEGA_CATEGORY_COVERAGE_PLAN = [
    {
        "mega_category_id": "home_appliances_laundry_climate",
        "engine_id": "home_living_appliances_engine",
        "display_name": "Home Appliances / Laundry / Climate",
        "coverage_status": "needs_deep_expansion",
        "coverage_depth_target": "deep_vertical_pack_v1",
        "department_seed_examples": [
            "refrigeration systems",
            "cooking and baking appliances",
            "dishwashing systems",
            "laundry appliances",
            "climate control systems",
            "vacuum and floor care",
            "water treatment appliances",
        ],
        "subcategory_seed_examples": [
            "fridge freezer combinations",
            "standalone freezers",
            "built-in ovens",
            "induction and ceramic hobs",
            "dishwashers",
            "washing machines",
            "washer dryers",
            "tumble dryers",
            "dehumidifiers and air purifiers",
            "portable and split air conditioners",
            "robotic vacuum cleaners",
            "steam cleaning systems",
        ],
        "product_family_seed_examples": [
            "multi-door refrigerators",
            "no-frost freezers",
            "pyrolytic ovens",
            "integrated dishwashers",
            "front load washing machines",
            "heat pump dryers",
            "energy class climate units",
            "air quality monitors",
            "bagless vacuum platforms",
            "upright steam mops",
            "water softener units",
        ],
        "spec_schema_seed_examples": [
            "capacity_liters",
            "energy_class",
            "annual_kwh_consumption",
            "noise_level_db",
            "program_count",
            "load_capacity_kg",
            "cooling_or_heating_btu",
            "coverage_area_m2",
            "smart_connectivity_support",
        ],
        "buying_priority_seed_examples": [
            "energy_efficiency",
            "household_size_fit",
            "serviceability_and_parts_availability",
            "installation_constraints",
            "noise_sensitivity",
            "lifecycle_reliability",
        ],
        "alias_seed_examples": [
            "white goods",
            "major home appliances",
            "laundry machines",
            "air treatment appliances",
            "floor care systems",
        ],
        "greeklish_seed_examples": [
            "psigeio no frost",
            "plintirio rouxon",
            "stegnotirio heat pump",
            "air condition inverter",
            "skoupa robot",
        ],
        "typo_seed_examples": [
            "psigio",
            "plintirioy",
            "stegnotirioy",
            "aircodition",
            "skouparobot",
        ],
        "intent_pattern_seed_examples": [
            "upgrade old appliance with lower consumption",
            "compare capacity for family home",
            "select appliance for small apartment footprint",
            "find quiet operation for night use",
            "match climate unit to room size",
        ],
        "ambiguity_risks": [
            "cleaning device terms overlap between vacuum, steam cleaner, and mop",
            "air treatment terms overlap between purifier, humidifier, and dehumidifier",
            "built-in vs freestanding appliance wording often omitted in queries",
        ],
        "safety_notes": [
            "do not present electrical installation advice as certified guidance",
            "highlight that final compatibility checks require official manuals",
            "avoid claims about medical-grade air treatment outcomes",
        ],
        "future_expansion_notes": [
            "expand by installation type, dimensions, and utility requirements",
            "add region-aware energy class normalization when deep packs are built",
            "extend with maintenance interval schemas for long lifecycle decisions",
        ],
    },
    {
        "mega_category_id": "kitchen_cooking_household",
        "engine_id": "home_living_appliances_engine",
        "display_name": "Kitchen / Cooking / Household",
        "coverage_status": "needs_deep_expansion",
        "coverage_depth_target": "deep_vertical_pack_v1",
        "department_seed_examples": [
            "small kitchen appliances",
            "food preparation systems",
            "coffee and beverage systems",
            "cookware and bakeware",
            "tabletop and storage",
            "household cleaning workflows",
        ],
        "subcategory_seed_examples": [
            "air fryers and mini ovens",
            "blenders and food processors",
            "mixers and kneading machines",
            "espresso and filter coffee machines",
            "kettles and toasters",
            "pots pans and pressure cookers",
            "food containers and preservation tools",
            "dish drying and sink organization",
            "cleaning chemicals and detergents",
            "household paper and disposal systems",
        ],
        "product_family_seed_examples": [
            "multi-function air fryer lines",
            "high-speed blender platforms",
            "planetary stand mixers",
            "bean-to-cup coffee machines",
            "manual brew systems",
            "induction-ready cookware sets",
            "non-stick frying pan families",
            "vacuum food storage kits",
            "modular pantry bins",
            "eco household cleaning concentrates",
        ],
        "spec_schema_seed_examples": [
            "power_watts",
            "bowl_or_tank_capacity_liters",
            "material_grade",
            "temperature_range_celsius",
            "dishwasher_safe",
            "food_contact_certification",
            "programmable_presets_count",
            "countertop_footprint_mm",
        ],
        "buying_priority_seed_examples": [
            "daily_workflow_speed",
            "ease_of_cleaning",
            "counter_space_constraints",
            "material_durability",
            "food_safety_support",
            "multi-use_versatility",
        ],
        "alias_seed_examples": [
            "kitchen helpers",
            "small appliances",
            "meal prep tools",
            "household essentials",
            "kitchen organization gear",
        ],
        "greeklish_seed_examples": [
            "air fryer gia spiti",
            "mixanima kafe espresso",
            "mixer zymis",
            "set katsaroles induction",
            "organosi kouzinas",
        ],
        "typo_seed_examples": [
            "airfryer",
            "espressso",
            "katsarolles",
            "organwsi kouzinas",
            "mixanima kafee",
        ],
        "intent_pattern_seed_examples": [
            "build compact kitchen workflow for studio",
            "choose easy-clean devices for daily use",
            "compare coffee systems by maintenance effort",
            "organize pantry for weekly meal planning",
            "reduce single-use supplies with reusable systems",
        ],
        "ambiguity_risks": [
            "terms like mixer overlap between kitchen and audio domains",
            "household word may refer to cleaning chemicals or appliances",
            "prep tools and cookware can overlap in mixed bundles",
        ],
        "safety_notes": [
            "avoid food safety guarantees beyond manufacturer specifications",
            "do not provide chemical handling instructions as authoritative advice",
            "separate electrical safety reminders from buying recommendations",
        ],
        "future_expansion_notes": [
            "deepen by cuisine workflow and household size contexts",
            "add accessory compatibility matrixes for kitchen ecosystems",
            "expand sustainability signals for packaging and reusability",
        ],
    },
    {
        "mega_category_id": "furniture_living_storage_smart_home",
        "engine_id": "home_living_appliances_engine",
        "display_name": "Furniture / Living / Storage / Smart Home",
        "coverage_status": "needs_deep_expansion",
        "coverage_depth_target": "deep_vertical_pack_v1",
        "department_seed_examples": [
            "living room furniture",
            "bedroom furniture",
            "office and study furniture",
            "storage and organization systems",
            "smart home control layers",
            "home climate automation",
        ],
        "subcategory_seed_examples": [
            "sofas and sectional seating",
            "beds mattresses and frames",
            "desks and ergonomic chairs",
            "wardrobes and modular shelving",
            "entryway storage systems",
            "lighting automation devices",
            "smart hubs and bridge devices",
            "security sensors and cameras",
            "smart thermostats and climate sensors",
            "motorized blinds and curtain controls",
        ],
        "product_family_seed_examples": [
            "modular sofa systems",
            "storage bed families",
            "sit-stand workstation lines",
            "stackable shelving ecosystems",
            "closet organizer kits",
            "zigbee and matter smart hubs",
            "indoor security camera ranges",
            "smart thermostat product lines",
            "automated lighting starter kits",
        ],
        "spec_schema_seed_examples": [
            "room_compatibility",
            "dimensions_mm",
            "material_finish",
            "load_capacity_kg",
            "assembly_complexity",
            "wireless_protocol_support",
            "voice_assistant_compatibility",
            "automation_scene_support",
        ],
        "buying_priority_seed_examples": [
            "space_optimization",
            "ergonomic_comfort",
            "storage_efficiency",
            "ecosystem_interoperability",
            "expandability_over_time",
            "maintenance_and_cleanability",
        ],
        "alias_seed_examples": [
            "living setup",
            "home organization systems",
            "smart living",
            "connected home controls",
            "space saving furniture",
        ],
        "greeklish_seed_examples": [
            "kanapes goniakos",
            "grafio ergonomiko",
            "ntoulapa me rafia",
            "smart home hub",
            "sensoras thermokrasias",
        ],
        "typo_seed_examples": [
            "kanappes",
            "ergonomiko grafeio",
            "rafia apothikefsis",
            "smarthome",
            "thermokrasia sensor",
        ],
        "intent_pattern_seed_examples": [
            "set up full living room for small apartment",
            "combine storage and style for family home",
            "choose smart ecosystem with low setup friction",
            "upgrade home office ergonomics for daily work",
            "automate lighting and climate routines",
        ],
        "ambiguity_risks": [
            "smart home accessories overlap with tech categories",
            "storage terms overlap between furniture and household tools",
            "security camera wording overlaps with media camera products",
        ],
        "safety_notes": [
            "avoid presenting security setup as guaranteed protection",
            "do not infer electrical wiring compatibility without official docs",
            "mark heavy-furniture installation as requiring proper mounting checks",
        ],
        "future_expansion_notes": [
            "expand style taxonomies by room type and household composition",
            "add protocol-level compatibility graphs for smart home devices",
            "introduce lifecycle notes for modular furniture reconfiguration",
        ],
    },
    {
        "mega_category_id": "phones_mobile_accessories",
        "engine_id": "tech_electronics_office_engine",
        "display_name": "Phones / Mobile / Accessories",
        "coverage_status": "partially_seeded",
        "coverage_depth_target": "deep_vertical_pack_v1",
        "department_seed_examples": [
            "smartphones and feature phones",
            "tablet and mobile compute",
            "mobile power and charging",
            "protection and carrying",
            "connectivity and wearables",
            "in-car mobile integrations",
        ],
        "subcategory_seed_examples": [
            "android and ios smartphone tiers",
            "rugged and enterprise phones",
            "tablets and digital pens",
            "power banks and battery packs",
            "wired and wireless chargers",
            "cases and screen protectors",
            "smartwatches and fitness bands",
            "mobile cables and adapters",
            "car mounts and charging docks",
            "portable hotspot devices",
        ],
        "product_family_seed_examples": [
            "flagship smartphone series",
            "midrange smartphone families",
            "compact smartphone lines",
            "high-capacity power bank families",
            "gan fast charger platforms",
            "magnetic wireless charger ecosystems",
            "impact-resistant case ranges",
            "multi-device charging station lines",
            "esim-ready wearable series",
        ],
        "spec_schema_seed_examples": [
            "display_size_inches",
            "chipset_generation",
            "ram_gb",
            "storage_gb",
            "battery_capacity_mah",
            "charging_protocol_support",
            "wireless_charging_support",
            "ip_rating",
            "usb_standard",
        ],
        "buying_priority_seed_examples": [
            "battery_life",
            "camera_performance",
            "charging_speed",
            "ecosystem_compatibility",
            "durability_for_daily_use",
            "software_support_horizon",
        ],
        "alias_seed_examples": [
            "mobile phones",
            "smartphone accessories",
            "portable charging",
            "phone protection gear",
            "mobile ecosystem devices",
        ],
        "greeklish_seed_examples": [
            "kinito me kali kamera",
            "power bank megali xorhtikotita",
            "fast charger usb c",
            "thiki kinhtou antikroustiki",
            "watch gia kinito",
        ],
        "typo_seed_examples": [
            "powr bank",
            "chargr usb c",
            "thiki kinitoy",
            "smatphone",
            "wirless charger",
        ],
        "intent_pattern_seed_examples": [
            "compare battery and charging for heavy travel",
            "select phone plus accessories as one compatibility bundle",
            "upgrade from older mobile ecosystem",
            "find robust setup for outdoor daily use",
            "balance performance and long-term software support",
        ],
        "ambiguity_risks": [
            "charger terms overlap with laptop and tool chargers",
            "power bank queries may refer to power stations",
            "watch terms overlap between smartwatches and fashion watches",
        ],
        "safety_notes": [
            "avoid unsafe battery handling suggestions",
            "state that charging safety follows certified device guidance",
            "do not claim water resistance beyond official ratings",
        ],
        "future_expansion_notes": [
            "expand by compatibility graphs across port and protocol versions",
            "add region-specific mobile network feature normalization",
            "deepen accessory bundles by usage mode and mobility context",
        ],
    },
    {
        "mega_category_id": "computers_office_peripherals",
        "engine_id": "tech_electronics_office_engine",
        "display_name": "Computers / Office / Peripherals",
        "coverage_status": "partially_seeded",
        "coverage_depth_target": "deep_vertical_pack_v1",
        "department_seed_examples": [
            "laptops and desktop systems",
            "monitors and displays",
            "input peripherals",
            "printing and scanning",
            "networking and office connectivity",
            "power and backup solutions",
        ],
        "subcategory_seed_examples": [
            "ultrabooks and workstation laptops",
            "desktop towers and mini pcs",
            "4k and ultrawide monitors",
            "mechanical and membrane keyboards",
            "ergonomic mice and trackballs",
            "multifunction printers and scanners",
            "calculators and office counting devices",
            "routers switches and mesh kits",
            "docking stations and hubs",
            "ups and surge protection units",
        ],
        "product_family_seed_examples": [
            "business laptop families",
            "creator workstation platforms",
            "high-refresh monitor lines",
            "office keyboard ranges",
            "vertical mouse families",
            "duplex scanner series",
            "scientific calculator families",
            "mesh wifi system lines",
            "usb c dock ecosystems",
        ],
        "spec_schema_seed_examples": [
            "cpu_class",
            "memory_gb",
            "storage_type",
            "screen_resolution",
            "refresh_rate_hz",
            "port_selection",
            "print_speed_ppm",
            "wireless_standard",
            "calculator_function_set",
        ],
        "buying_priority_seed_examples": [
            "productivity_performance",
            "multi-device_connectivity",
            "ergonomic_long_session_use",
            "expandability",
            "support_and_service_availability",
            "energy_efficiency",
        ],
        "alias_seed_examples": [
            "office hardware",
            "workstation setup",
            "computer accessories",
            "office peripherals",
            "work from home equipment",
        ],
        "greeklish_seed_examples": [
            "laptop gia douleia",
            "othoni 4k grafeiou",
            "ergonomiko pontiki",
            "ektypotis polymixanima",
            "arithmomixani scientific",
        ],
        "typo_seed_examples": [
            "lapotp",
            "ergonomiko pontiiki",
            "polimixanima",
            "arithmomhxani",
            "ultrawde monitor",
        ],
        "intent_pattern_seed_examples": [
            "set up hybrid office with reliable peripherals",
            "compare laptop and monitor combo for productivity",
            "pick durable hardware for daily long sessions",
            "upgrade networking for multi-room office",
            "build office toolkit including calculator and printer",
        ],
        "ambiguity_risks": [
            "dock term may refer to mobile or laptop contexts",
            "calculator term overlaps with app-level software queries",
            "office setup term can include furniture in another engine",
        ],
        "safety_notes": [
            "avoid presenting data security promises as guaranteed outcomes",
            "clarify electrical load limits for ups and surge setups",
            "do not provide repair instructions as certified service advice",
        ],
        "future_expansion_notes": [
            "expand compatibility matrices for ports and docking scenarios",
            "add workflow-first profiles for coding, design, and admin tasks",
            "deepen network and power reliability attributes by office size",
        ],
    },
    {
        "mega_category_id": "audio_video_gaming_cameras",
        "engine_id": "tech_electronics_office_engine",
        "display_name": "Audio / Video / Gaming / Cameras",
        "coverage_status": "needs_deep_expansion",
        "coverage_depth_target": "deep_vertical_pack_v1",
        "department_seed_examples": [
            "home audio systems",
            "tv and display devices",
            "gaming platforms and accessories",
            "camera and imaging systems",
            "streaming and creator hardware",
            "media storage and playback",
        ],
        "subcategory_seed_examples": [
            "soundbars and multi-speaker setups",
            "oled and qled televisions",
            "gaming consoles and controllers",
            "pc gaming accessories",
            "mirrorless and dslr cameras",
            "action cameras",
            "lenses and stabilization gear",
            "microphones and capture cards",
            "media streaming devices",
            "home theater receivers",
        ],
        "product_family_seed_examples": [
            "cinema soundbar lines",
            "high refresh gaming monitor families",
            "pro controller ecosystems",
            "entry mirrorless camera ranges",
            "creator microphone product lines",
            "compact action camera families",
            "wireless home theater sets",
            "streaming box platforms",
            "camera gimbal lines",
        ],
        "spec_schema_seed_examples": [
            "resolution_standard",
            "panel_technology",
            "audio_channel_configuration",
            "refresh_rate_hz",
            "latency_ms",
            "sensor_size",
            "video_recording_profile",
            "stabilization_support",
            "connectivity_ports",
        ],
        "buying_priority_seed_examples": [
            "media_quality",
            "gaming_responsiveness",
            "creator_workflow_fit",
            "upgrade_compatibility",
            "setup_complexity",
            "long-term_platform_support",
        ],
        "alias_seed_examples": [
            "entertainment systems",
            "home theater gear",
            "gaming setup",
            "content creator kit",
            "camera gear",
        ],
        "greeklish_seed_examples": [
            "tileorasi oled",
            "soundbar gia saloni",
            "kamera mirrorless",
            "gaming controller wireless",
            "mikrofono streaming",
        ],
        "typo_seed_examples": [
            "sounbar",
            "mirorless",
            "contorller",
            "tileorasi qledd",
            "streamng box",
        ],
        "intent_pattern_seed_examples": [
            "build living room entertainment upgrade path",
            "compare creator camera setups for video workflow",
            "optimize gaming station with low latency gear",
            "match tv and audio ecosystem compatibility",
            "plan hybrid media and streaming setup",
        ],
        "ambiguity_risks": [
            "camera accessories can overlap with security cameras",
            "gaming accessories can overlap with office peripherals",
            "audio terms overlap with mobile audio devices",
        ],
        "safety_notes": [
            "avoid hearing-protection claims that imply medical guidance",
            "do not claim surveillance suitability for consumer cameras",
            "state mounting and electrical setup requires proper instructions",
        ],
        "future_expansion_notes": [
            "expand creator vs entertainment intent segmentation",
            "add compatibility maps for console, pc, and display standards",
            "deepen camera ecosystems by lens mount and workflow type",
        ],
    },
    {
        "mega_category_id": "car_parts_service_maintenance",
        "engine_id": "auto_moto_mobility_engine",
        "display_name": "Car Parts / Service / Maintenance",
        "coverage_status": "needs_deep_expansion",
        "coverage_depth_target": "deep_vertical_pack_v1",
        "department_seed_examples": [
            "engine and drivetrain components",
            "braking and suspension systems",
            "service fluids and filters",
            "diagnostic and maintenance tools",
            "electrical and lighting systems",
            "seasonal maintenance workflows",
        ],
        "subcategory_seed_examples": [
            "oil and air filters",
            "spark plugs and ignition components",
            "brake pads and discs",
            "shock absorbers and springs",
            "engine oils and coolants",
            "battery and charging system parts",
            "obd diagnostics tools",
            "wiper systems and visibility parts",
            "timing components",
            "service kits by mileage interval",
        ],
        "product_family_seed_examples": [
            "maintenance filter kit families",
            "performance brake pad lines",
            "long-life coolant formulations",
            "agm and efb battery ranges",
            "consumer obd scanner platforms",
            "timing belt kit ecosystems",
            "winter visibility maintenance packs",
            "drivetrain service component lines",
        ],
        "spec_schema_seed_examples": [
            "vehicle_fitment_scope",
            "engine_code_compatibility",
            "service_interval_km",
            "fluid_viscosity_grade",
            "temperature_operating_range",
            "certification_standard",
            "installation_difficulty",
            "warranty_scope",
        ],
        "buying_priority_seed_examples": [
            "fitment_accuracy",
            "service_interval_alignment",
            "safety_relevance",
            "durability_under_driving_conditions",
            "availability_of_supporting_parts",
            "maintenance_cost_over_time",
        ],
        "alias_seed_examples": [
            "car service parts",
            "vehicle maintenance items",
            "auto replacement components",
            "scheduled service consumables",
            "garage essentials",
        ],
        "greeklish_seed_examples": [
            "filtra ladiou autokinito",
            "takakia frenon",
            "mpataria autokinitou",
            "diaghostiko obd",
            "service kit km",
        ],
        "typo_seed_examples": [
            "takakiafrenon",
            "filtro ladioy",
            "mpataria autokinitoy",
            "obd diaghnostiko",
            "srevice kit",
        ],
        "intent_pattern_seed_examples": [
            "prepare maintenance checklist before long trip",
            "compare replacement parts by compatibility and durability",
            "align service components with vehicle mileage",
            "improve braking reliability for daily commuting",
            "bundle essential maintenance items for seasonal change",
        ],
        "ambiguity_risks": [
            "service term can refer to workshop booking instead of parts",
            "battery term overlaps with mobile electronics category",
            "filter term overlaps with household appliances and water systems",
        ],
        "safety_notes": [
            "do not provide legal roadworthiness judgments",
            "mark that installation may require certified technicians",
            "avoid implying guaranteed safety outcomes from single component swaps",
        ],
        "future_expansion_notes": [
            "expand fitment ontology by make, model, generation, and engine code",
            "add maintenance timeline profiles by usage intensity",
            "deepen safety-critical part validation prompts",
        ],
    },
    {
        "mega_category_id": "tyres_wheels_car_accessories",
        "engine_id": "auto_moto_mobility_engine",
        "display_name": "Tyres / Wheels / Car Accessories",
        "coverage_status": "partially_seeded",
        "coverage_depth_target": "deep_vertical_pack_v1",
        "department_seed_examples": [
            "tyre fitment and seasonal tyres",
            "wheel and rim systems",
            "winter readiness accessories",
            "interior comfort accessories",
            "exterior protection accessories",
            "car utility and transport accessories",
        ],
        "subcategory_seed_examples": [
            "summer all-season and winter tyres",
            "performance and touring tyres",
            "steel and alloy wheels",
            "tpms and wheel maintenance",
            "snow chains and traction aids",
            "seat covers and organizers",
            "boot storage and transport systems",
            "dash camera and holder accessories",
            "car cleaning and detailing kits",
            "sun protection accessories",
        ],
        "product_family_seed_examples": [
            "touring tyre family lines",
            "high-grip winter tyre platforms",
            "lightweight alloy rim families",
            "tpms sensor sets",
            "compact snow chain systems",
            "modular trunk organizer ranges",
            "all-weather floor mat lines",
            "vehicle detailing starter kits",
            "multi-point phone mount systems",
        ],
        "spec_schema_seed_examples": [
            "tyre_size_code",
            "load_index",
            "speed_rating",
            "seasonal_class",
            "wheel_diameter_inch",
            "rim_width",
            "offset_et",
            "material_finish",
            "vehicle_segment_compatibility",
        ],
        "buying_priority_seed_examples": [
            "road_safety_and_grip",
            "fitment_precision",
            "weather_suitability",
            "ride_comfort",
            "durability_and_wear_profile",
            "accessory_practicality",
        ],
        "alias_seed_examples": [
            "car tyres and rims",
            "wheel setup",
            "car add-ons",
            "vehicle accessories",
            "seasonal traction gear",
        ],
        "greeklish_seed_examples": [
            "elastika xeimoniatika",
            "zantes alouminiou",
            "alysides xioniou",
            "kalymmata kathismaton",
            "organosi portbagkaz",
        ],
        "typo_seed_examples": [
            "elastica xeimoniatika",
            "zantedes",
            "alysides xonioy",
            "portbagaz",
            "kalimata kathismaton",
        ],
        "intent_pattern_seed_examples": [
            "match tyre setup for local seasonal weather",
            "check wheel fitment compatibility before purchase",
            "prepare complete winter driving accessory pack",
            "upgrade interior utility for family travel",
            "balance comfort and performance for daily commuting",
        ],
        "ambiguity_risks": [
            "wheel size terms can be confused with bicycle sizes",
            "accessory queries can overlap with general electronics accessories",
            "winter gear terms overlap with mobility and outdoor categories",
        ],
        "safety_notes": [
            "do not provide legal compliance decisions for road regulations",
            "state tyre and wheel installation requires professional verification",
            "avoid promising braking or handling outcomes",
        ],
        "future_expansion_notes": [
            "deepen fitment guardrails with manufacturer homologation references",
            "expand regional weather profiles for tyre recommendation intents",
            "add maintenance lifecycle support for wear and replacement timing",
        ],
    },
    {
        "mega_category_id": "moto_bicycle_mobility_gear",
        "engine_id": "auto_moto_mobility_engine",
        "display_name": "Moto / Bicycle / Mobility Gear",
        "coverage_status": "needs_deep_expansion",
        "coverage_depth_target": "deep_vertical_pack_v1",
        "department_seed_examples": [
            "motorcycle parts and protection",
            "bicycle components and upgrades",
            "rider safety equipment",
            "urban commuting mobility gear",
            "maintenance and workshop kits",
            "cargo and travel systems",
        ],
        "subcategory_seed_examples": [
            "moto helmets and jackets",
            "moto gloves and boots",
            "bicycle drivetrains and brakes",
            "bicycle lights and navigation",
            "electric scooter accessories",
            "commuter visibility gear",
            "repair stands and tool kits",
            "panniers and cargo racks",
            "child transport attachments",
            "anti-theft and locking systems",
        ],
        "product_family_seed_examples": [
            "full-face helmet families",
            "urban riding jacket ranges",
            "hydraulic brake set lines",
            "commuter lighting system families",
            "high-security lock platforms",
            "cargo rack ecosystems",
            "portable mobility repair kits",
            "reflective safety apparel lines",
            "waterproof pannier ranges",
        ],
        "spec_schema_seed_examples": [
            "vehicle_type_compatibility",
            "helmet_certification",
            "size_and_fit_range",
            "visibility_rating",
            "water_resistance_level",
            "load_capacity_kg",
            "brake_system_type",
            "mounting_interface",
            "security_class",
        ],
        "buying_priority_seed_examples": [
            "rider_safety",
            "fit_and_comfort",
            "commute_reliability",
            "weather_readiness",
            "maintenance_simplicity",
            "cargo_and_transport_needs",
        ],
        "alias_seed_examples": [
            "moto gear",
            "bike commuting equipment",
            "mobility accessories",
            "rider protection kit",
            "urban mobility setup",
        ],
        "greeklish_seed_examples": [
            "kranos moto",
            "fota podilatou",
            "gantzia podilatou cargo",
            "kleidaria asfaleias podilatou",
            "jaketa anavath",
        ],
        "typo_seed_examples": [
            "krano moto",
            "podhlatou fota",
            "kleidaria asfalias",
            "jaketa anabati",
            "scooter aksesoir",
        ],
        "intent_pattern_seed_examples": [
            "build safe daily commute gear package",
            "upgrade bicycle braking and lighting for city use",
            "select moto protective kit for mixed weather",
            "organize cargo solutions for weekend rides",
            "improve anti-theft setup for urban parking",
        ],
        "ambiguity_risks": [
            "mobility gear overlaps with sports and outdoor categories",
            "helmet terms overlap with construction safety gear",
            "light terms overlap with general electronics lighting",
        ],
        "safety_notes": [
            "avoid certifying legal riding compliance claims",
            "state that protective gear does not eliminate risk",
            "do not provide mechanical repair procedures as expert instruction",
        ],
        "future_expansion_notes": [
            "expand by riding discipline and trip-distance personas",
            "add compatibility mappings for frames, mounts, and standards",
            "deepen safety-context prompts by environment and speed profile",
        ],
    },
    {
        "mega_category_id": "power_tools_workshop",
        "engine_id": "tools_diy_garden_repair_engine",
        "display_name": "Power Tools / Workshop",
        "coverage_status": "needs_deep_expansion",
        "coverage_depth_target": "deep_vertical_pack_v1",
        "department_seed_examples": [
            "drilling and fastening tools",
            "cutting and shaping tools",
            "sanding and surface preparation",
            "workshop stationary machines",
            "tool batteries and charging ecosystems",
            "dust extraction and workshop safety",
            "jobsite lighting and power distribution",
        ],
        "subcategory_seed_examples": [
            "hammer drills and rotary hammers",
            "impact drivers and screw guns",
            "circular and plunge saws",
            "jigsaws and reciprocating saws",
            "angle grinders and polishers",
            "random orbital and belt sanders",
            "table saws and mitre saws",
            "drill presses and benchtop grinders",
            "cordless battery platforms",
            "tool chargers and battery diagnostics",
            "industrial vacuum and extraction systems",
            "workshop compressor and pneumatic starters",
        ],
        "product_family_seed_examples": [
            "18v cordless combo lines",
            "high-torque impact driver families",
            "precision plunge saw ranges",
            "compact orbital sander lines",
            "workshop table saw platforms",
            "bench grinder ecosystems",
            "multi-port smart charger lines",
            "dust extraction unit families",
            "jobsite led lighting systems",
            "pneumatic starter compressor kits",
        ],
        "spec_schema_seed_examples": [
            "power_source",
            "battery_voltage",
            "battery_capacity_ah",
            "motor_type",
            "no_load_speed_rpm",
            "torque_nm",
            "cutting_depth_mm",
            "disc_or_blade_diameter_mm",
            "dust_collection_support",
            "tool_weight_kg",
        ],
        "buying_priority_seed_examples": [
            "tool_platform_compatibility",
            "power_to_weight_balance",
            "precision_and_control",
            "continuous_use_reliability",
            "workshop_safety_support",
            "serviceability_and_spare_parts",
            "expandable_tool_ecosystem",
        ],
        "alias_seed_examples": [
            "electric tools",
            "cordless workshop tools",
            "professional workshop gear",
            "build and repair machines",
            "jobsite power tools",
        ],
        "greeklish_seed_examples": [
            "dril kroustiko",
            "pagospriono workshop",
            "systhma mpatarias 18v",
            "goniakos troxos",
            "anarrofhths skonis ergastiriou",
        ],
        "typo_seed_examples": [
            "drll kroustiko",
            "pagospriono",
            "goniakos trohos",
            "workshop anarrofitis",
            "impakt driver",
        ],
        "intent_pattern_seed_examples": [
            "build workshop platform with shared batteries",
            "compare cutting tools for precision wood projects",
            "set up safe dust-managed workspace",
            "choose durable tools for frequent renovation jobs",
            "expand from starter kit to advanced workshop stack",
        ],
        "ambiguity_risks": [
            "drill and driver terms overlap between power and hand tools",
            "battery terms overlap with auto and mobile categories",
            "workshop machine terms can overlap with industrial equipment",
        ],
        "safety_notes": [
            "do not provide procedural operating guidance as certified training",
            "highlight need for personal protective equipment and manual checks",
            "avoid claims of injury prevention guarantees",
        ],
        "future_expansion_notes": [
            "expand by trade workflow such as carpentry, metal, and renovation",
            "add cross-platform battery compatibility guardrails",
            "deepen maintenance and calibration lifecycle data",
        ],
    },
    {
        "mega_category_id": "hand_tools_consumables_measuring",
        "engine_id": "tools_diy_garden_repair_engine",
        "display_name": "Hand Tools / Consumables / Measuring",
        "coverage_status": "needs_deep_expansion",
        "coverage_depth_target": "deep_vertical_pack_v1",
        "department_seed_examples": [
            "manual fastening and gripping tools",
            "cutting and finishing hand tools",
            "abrasives and consumables",
            "fasteners and fixings",
            "measurement and layout instruments",
            "adhesives and repair compounds",
            "electrical hand tools",
        ],
        "subcategory_seed_examples": [
            "screwdrivers and bit sets",
            "pliers and clamps",
            "hammers and chisels",
            "hand saws and utility knives",
            "sandpaper and polishing consumables",
            "screws anchors and bolts",
            "laser distance meters",
            "spirit levels and squares",
            "multimeters and test pens",
            "sealants and epoxy compounds",
            "thread repair kits",
        ],
        "product_family_seed_examples": [
            "precision screwdriver kit families",
            "heavy-duty plier lines",
            "framing hammer ranges",
            "bi-metal hand saw families",
            "abrasive grit assortment packs",
            "mixed fastener organizer kits",
            "laser measure product lines",
            "digital multimeter families",
            "construction adhesive lines",
            "metal epoxy repair ranges",
        ],
        "spec_schema_seed_examples": [
            "material_composition",
            "size_range",
            "torque_or_force_rating",
            "measurement_accuracy",
            "battery_or_power_requirement",
            "corrosion_resistance",
            "temperature_tolerance",
            "set_piece_count",
            "application_surface_type",
        ],
        "buying_priority_seed_examples": [
            "precision_requirements",
            "durability_under_repeated_use",
            "task_specific_fit",
            "restock_frequency",
            "safety_and_insulation_requirements",
            "organization_and_portability",
        ],
        "alias_seed_examples": [
            "manual tools",
            "workshop essentials",
            "fixing supplies",
            "measuring kit",
            "repair consumables",
        ],
        "greeklish_seed_examples": [
            "set katsavidiwn",
            "penses kai sfiktires",
            "vides kai oupa",
            "metritis laser",
            "polymetro gia ilektrika",
        ],
        "typo_seed_examples": [
            "katsaviddia",
            "sfiktires",
            "vdes kai oupa",
            "laser metriths",
            "polimetro",
        ],
        "intent_pattern_seed_examples": [
            "assemble complete manual repair toolkit",
            "restock fasteners and consumables by project type",
            "improve measuring accuracy before installation tasks",
            "pick insulated tools for safe electrical work",
            "bundle portable essentials for field repairs",
        ],
        "ambiguity_risks": [
            "meter term overlaps with utility billing contexts",
            "consumables can overlap with office and household categories",
            "repair kits can overlap with automotive maintenance kits",
        ],
        "safety_notes": [
            "avoid electrical safety guarantees for tool usage",
            "state that measurement errors can impact build safety",
            "do not provide structural repair certification claims",
        ],
        "future_expansion_notes": [
            "expand by material workflows such as wood, metal, and masonry",
            "add dependency chains between tools, consumables, and fixings",
            "deepen task-level schema templates for precision planning",
        ],
    },
    {
        "mega_category_id": "garden_outdoor_repair_building",
        "engine_id": "tools_diy_garden_repair_engine",
        "display_name": "Garden / Outdoor / Repair / Building",
        "coverage_status": "needs_deep_expansion",
        "coverage_depth_target": "deep_vertical_pack_v1",
        "department_seed_examples": [
            "garden maintenance systems",
            "outdoor power equipment",
            "irrigation and water management",
            "building materials and structural repair",
            "fencing and exterior infrastructure",
            "outdoor cleaning and restoration",
            "seasonal property care workflows",
        ],
        "subcategory_seed_examples": [
            "lawn mowers and trimmers",
            "chainsaws and hedge trimmers",
            "leaf blowers and vacuums",
            "watering timers and drip irrigation",
            "hoses connectors and pumps",
            "cement mortar and patch compounds",
            "wood treatment and weatherproof coatings",
            "roof and gutter maintenance tools",
            "pressure washers and accessories",
            "fence repair kits and gate hardware",
            "outdoor storage sheds and organization",
            "pest control and garden protection",
        ],
        "product_family_seed_examples": [
            "battery garden tool platforms",
            "petrol brush cutter lines",
            "programmable irrigation controller ranges",
            "high-pressure washer families",
            "quick-set repair mortar lines",
            "weatherproof decking treatment series",
            "modular fence system families",
            "outdoor maintenance kit bundles",
            "gutter cleaning tool ranges",
        ],
        "spec_schema_seed_examples": [
            "terrain_or_surface_fit",
            "motor_power_watts",
            "cutting_width_cm",
            "battery_runtime_minutes",
            "water_flow_rate",
            "pressure_bar",
            "weather_resistance_level",
            "material_compatibility",
            "seasonal_use_profile",
        ],
        "buying_priority_seed_examples": [
            "property_size_fit",
            "seasonal_maintenance_load",
            "durability_for_outdoor_conditions",
            "repair_readiness",
            "tool_and_material_compatibility",
            "ease_of_storage_and_transport",
        ],
        "alias_seed_examples": [
            "garden tools",
            "outdoor maintenance gear",
            "building and repair supplies",
            "yard care equipment",
            "property upkeep systems",
        ],
        "greeklish_seed_examples": [
            "xortokoptiko kipou",
            "alysopriono exoterikou xorou",
            "systima potismatos drip",
            "piestiko nerou",
            "ylika episkevis exoterikou toixou",
        ],
        "typo_seed_examples": [
            "xortokoptiko",
            "alysoprino",
            "potisma drip",
            "piestiko nero",
            "episkevi exoterikou",
        ],
        "intent_pattern_seed_examples": [
            "plan full seasonal garden maintenance stack",
            "equip outdoor repair workflow for property upkeep",
            "compare irrigation systems for water efficiency",
            "choose heavy-duty tools for large outdoor spaces",
            "bundle cleaning and restoration for exterior surfaces",
        ],
        "ambiguity_risks": [
            "outdoor gear overlaps with sports and lifestyle categories",
            "repair materials overlap with indoor renovation contexts",
            "pump and hose terms overlap with automotive cleaning products",
        ],
        "safety_notes": [
            "do not provide structural engineering guidance",
            "mark power equipment operation as requiring manual compliance",
            "avoid pesticide and chemical use claims beyond labels",
        ],
        "future_expansion_notes": [
            "expand by climate zone and seasonal workloads",
            "add project-first templates for decking, fencing, and irrigation",
            "deepen cross-category dependency links for build workflows",
        ],
    },
    {
        "mega_category_id": "health_wellness_safety_devices",
        "engine_id": "health_beauty_family_lifestyle_engine",
        "display_name": "Health / Wellness / Safety Devices",
        "coverage_status": "needs_deep_expansion",
        "coverage_depth_target": "deep_vertical_pack_v1",
        "department_seed_examples": [
            "wellness monitoring devices",
            "home diagnostic support devices",
            "mobility and rehabilitation support",
            "sleep and recovery systems",
            "household safety monitoring",
            "preventive care equipment",
        ],
        "subcategory_seed_examples": [
            "blood pressure monitors",
            "glucometer support devices",
            "pulse oximeters and thermometers",
            "smart wellness trackers",
            "posture and mobility aids",
            "tens and relief devices",
            "sleep quality support devices",
            "air quality safety detectors",
            "fall alert and emergency support devices",
            "home first-aid organization systems",
        ],
        "product_family_seed_examples": [
            "upper arm bp monitor lines",
            "connected wellness tracker families",
            "infrared thermometer ranges",
            "portable pulse oximeter lines",
            "mobility support cane families",
            "recovery stimulation device ranges",
            "sleep routine aid product lines",
            "co and smoke detector families",
            "safety alert wearable lines",
        ],
        "spec_schema_seed_examples": [
            "measurement_scope",
            "accuracy_class",
            "calibration_support",
            "battery_life",
            "display_readability",
            "data_sync_support",
            "alert_threshold_support",
            "intended_use_context",
            "certification_markings",
        ],
        "buying_priority_seed_examples": [
            "measurement_reliability",
            "ease_of_daily_use",
            "readability_for_family_members",
            "maintenance_and_calibration_needs",
            "safety_alert_clarity",
            "privacy_of_device_data",
        ],
        "alias_seed_examples": [
            "home health devices",
            "wellness monitors",
            "safety detectors",
            "preventive care equipment",
            "family health support gear",
        ],
        "greeklish_seed_examples": [
            "piesometro broxiona",
            "thermometro yperythron",
            "oxymetro daktylou",
            "systhma paragolouthisis ygeias",
            "anixneftis kapnou",
        ],
        "typo_seed_examples": [
            "piessometro",
            "thermometro yperithron",
            "oximetro",
            "anixneftis kapnoy",
            "parakolouthisi ygeias",
        ],
        "intent_pattern_seed_examples": [
            "set up home wellness tracking routine",
            "choose readable monitoring devices for older users",
            "build household safety detection baseline",
            "compare ease of use for daily health checks",
            "select low-maintenance preventive support equipment",
        ],
        "ambiguity_risks": [
            "medical and wellness terms can overlap with clinical contexts",
            "safety detector terms overlap with smart home devices",
            "tracker terms overlap with fitness and sports wearables",
        ],
        "safety_notes": [
            "do not provide diagnosis or treatment recommendations",
            "state that readings are support data, not clinical decisions",
            "avoid suggesting replacement of professional medical advice",
        ],
        "future_expansion_notes": [
            "expand by household profile and preventive routine depth",
            "add calibration and data quality workflow templates",
            "deepen safety-device interoperability with home systems",
        ],
    },
    {
        "mega_category_id": "beauty_grooming_personal_care",
        "engine_id": "health_beauty_family_lifestyle_engine",
        "display_name": "Beauty / Grooming / Personal Care",
        "coverage_status": "needs_deep_expansion",
        "coverage_depth_target": "deep_vertical_pack_v1",
        "department_seed_examples": [
            "skin care and treatment routines",
            "hair care and styling",
            "grooming devices",
            "oral and body care",
            "fragrance and self-care",
            "travel and daily care kits",
        ],
        "subcategory_seed_examples": [
            "cleansers toners and moisturizers",
            "serums and targeted treatments",
            "shampoo conditioner and masks",
            "hair styling tools",
            "electric shavers and trimmers",
            "epilators and beauty devices",
            "oral care devices",
            "body care and hygiene products",
            "sensitive skin care options",
            "men and women grooming kits",
        ],
        "product_family_seed_examples": [
            "hydration skincare lines",
            "anti-frizz hair care families",
            "ionic hair dryer ranges",
            "precision trimmer platforms",
            "sonic oral care device lines",
            "body care routine collections",
            "sensitive-skin formula ranges",
            "travel grooming bundle lines",
            "daily grooming starter kits",
        ],
        "spec_schema_seed_examples": [
            "skin_or_hair_type",
            "active_ingredient_profile",
            "dermatology_tested",
            "power_or_runtime",
            "blade_or_head_type",
            "water_resistance",
            "sensitivity_mode_support",
            "routine_frequency",
            "travel_compliance_size",
        ],
        "buying_priority_seed_examples": [
            "skin_or_hair_compatibility",
            "gentle_daily_use",
            "hygiene_and_cleanability",
            "portability",
            "routine_consistency",
            "long-term_cost_efficiency",
        ],
        "alias_seed_examples": [
            "personal care",
            "beauty routine products",
            "grooming essentials",
            "daily self-care kit",
            "skin and hair care",
        ],
        "greeklish_seed_examples": [
            "krema prosopou entydatikh",
            "syshthma peripoiisis mallion",
            "xyristiki mixani",
            "vourtsa dontion ilektriki",
            "set grooming taxidiou",
        ],
        "typo_seed_examples": [
            "krema prosopoy",
            "peripoiisi mallion",
            "xyristikh mixanh",
            "ilektrikh vourtsa",
            "groming set",
        ],
        "intent_pattern_seed_examples": [
            "build complete daily skincare workflow",
            "choose grooming device for sensitive skin",
            "compare hair care options for frequent styling",
            "optimize travel-friendly personal care setup",
            "create low-maintenance routine for busy schedule",
        ],
        "ambiguity_risks": [
            "device terms overlap between beauty and health monitoring",
            "care terms overlap with baby and family categories",
            "sensitive term can indicate allergies requiring caution",
        ],
        "safety_notes": [
            "avoid medical claims for cosmetic products",
            "do not provide dermatological diagnosis guidance",
            "state that allergy checks should follow official instructions",
        ],
        "future_expansion_notes": [
            "expand by routine stage and user profile segmentation",
            "add ingredient ontology for compatibility and exclusions",
            "deepen appliance accessory and replacement part mappings",
        ],
    },
    {
        "mega_category_id": "baby_kids_pets_sports_outdoor",
        "engine_id": "health_beauty_family_lifestyle_engine",
        "display_name": "Baby / Kids / Pets / Sports / Outdoor",
        "coverage_status": "needs_deep_expansion",
        "coverage_depth_target": "deep_vertical_pack_v1",
        "department_seed_examples": [
            "baby transport and care",
            "kids development and school routines",
            "pet feeding and hygiene",
            "sports training equipment",
            "outdoor recreation gear",
            "family travel and activity support",
        ],
        "subcategory_seed_examples": [
            "strollers and travel systems",
            "feeding and nursery essentials",
            "car seats and child mobility safety",
            "educational and creative play tools",
            "pet nutrition and feeding systems",
            "pet grooming and habitat care",
            "home fitness and training accessories",
            "camping and hiking essentials",
            "cycling and recreation accessories",
            "hydration and recovery support gear",
        ],
        "product_family_seed_examples": [
            "modular stroller systems",
            "convertible car seat lines",
            "nursery care starter families",
            "school routine backpack platforms",
            "automatic pet feeder ranges",
            "pet grooming station lines",
            "home workout kit families",
            "camping shelter product lines",
            "outdoor hydration system ranges",
        ],
        "spec_schema_seed_examples": [
            "age_or_size_range",
            "safety_certification_scope",
            "material_safety_profile",
            "load_capacity_kg",
            "portability_weight",
            "weather_resistance",
            "activity_intensity_fit",
            "care_and_cleaning_requirements",
            "storage_footprint",
        ],
        "buying_priority_seed_examples": [
            "family_safety",
            "comfort_for_long_use",
            "durability_for_active_routines",
            "easy_cleaning",
            "portability_and_storage",
            "multi-use_flexibility",
        ],
        "alias_seed_examples": [
            "family essentials",
            "baby and kids gear",
            "pet care products",
            "sports and outdoor equipment",
            "active lifestyle gear",
        ],
        "greeklish_seed_examples": [
            "karotsi moro",
            "kathisma autokinitou paidi",
            "taistra gatias automati",
            "set gymnastikis spiti",
            "eksoplismos camping",
        ],
        "typo_seed_examples": [
            "karotsi moroou",
            "kathisma paidiou autokinitou",
            "taistra gatas",
            "gymnastikh spiti",
            "campig eksoplismos",
        ],
        "intent_pattern_seed_examples": [
            "build complete family weekend outdoor pack",
            "select safe transport setup for baby and toddler",
            "equip pet care routine for daily work schedule",
            "combine sports and recovery equipment for home use",
            "choose durable gear for active family lifestyle",
        ],
        "ambiguity_risks": [
            "outdoor gear overlaps with garden and repair category",
            "mobility terms overlap with auto and commute categories",
            "care terms overlap with health and beauty categories",
        ],
        "safety_notes": [
            "do not provide child safety legal certification judgments",
            "avoid veterinary or medical treatment recommendations",
            "state that activity gear suitability depends on supervision and context",
        ],
        "future_expansion_notes": [
            "expand by lifecycle stage from infant to teen and pet maturity",
            "add activity-specific sports and outdoor decision trees",
            "deepen family profile-based prioritization rules",
        ],
    },
    {
        "mega_category_id": "clothing_apparel_workwear",
        "engine_id": "fashion_footwear_jewelry_accessories_engine",
        "display_name": "Clothing / Apparel / Workwear",
        "coverage_status": "needs_deep_expansion",
        "coverage_depth_target": "deep_vertical_pack_v1",
        "department_seed_examples": [
            "everyday apparel",
            "formal and occasion wear",
            "athleisure and performance clothing",
            "seasonal outerwear",
            "professional workwear and uniforms",
            "plus-size and inclusive fit ranges",
            "technical fabric systems",
        ],
        "subcategory_seed_examples": [
            "tops shirts and blouses",
            "trousers jeans and chinos",
            "dresses and skirts",
            "suits and tailoring",
            "jackets coats and parkas",
            "sportswear sets",
            "medical and industrial workwear",
            "high-visibility clothing",
            "thermal base layers",
            "maternity and adaptive apparel",
            "occasion capsule collections",
            "rainwear and weatherproof layers",
        ],
        "product_family_seed_examples": [
            "capsule wardrobe basics lines",
            "performance running apparel families",
            "breathable work uniform ranges",
            "flame-resistant workwear lines",
            "waterproof shell jacket families",
            "tailored formalwear product lines",
            "stretch denim family ranges",
            "adaptive fit apparel lines",
            "insulated winter layering systems",
            "uv-protection summer apparel ranges",
        ],
        "spec_schema_seed_examples": [
            "fit_profile",
            "size_standard",
            "fabric_composition",
            "breathability_rating",
            "water_resistance_level",
            "insulation_weight",
            "care_instruction_class",
            "certified_workwear_standard",
            "seasonality_profile",
        ],
        "buying_priority_seed_examples": [
            "fit_and_comfort",
            "fabric_durability",
            "seasonal_appropriateness",
            "professional_requirement_match",
            "wardrobe_interoperability",
            "care_maintenance_effort",
            "inclusive_sizing_availability",
        ],
        "alias_seed_examples": [
            "fashion clothing",
            "apparel collections",
            "work uniforms",
            "seasonal wardrobe",
            "outfit basics",
            "daily wear",
        ],
        "greeklish_seed_examples": [
            "rouxa kathimerina",
            "epaggelmatika rouxa",
            "jacket xeimoniatiko",
            "athlitika set",
            "formal koustoumi",
            "rouxa plus size",
        ],
        "typo_seed_examples": [
            "rouha kathimerina",
            "epagelmatika rouxa",
            "xeimoniatiko jaket",
            "athlitika sett",
            "koustoumi formal",
            "plussize rouxa",
        ],
        "intent_pattern_seed_examples": [
            "build full seasonal wardrobe across work and casual",
            "compare fabric durability for daily commute use",
            "select compliant workwear for specific job conditions",
            "plan capsule wardrobe with interchangeable outfits",
            "find inclusive fit options without style compromise",
        ],
        "ambiguity_risks": [
            "workwear can overlap with safety gear in tools categories",
            "sport apparel overlaps with sports lifestyle mega-category",
            "formalwear terms overlap with accessories and footwear bundles",
        ],
        "safety_notes": [
            "do not claim certified protection unless standards are explicit",
            "avoid body or health outcome claims from apparel",
            "mark that fit and comfort are subjective and user-dependent",
        ],
        "future_expansion_notes": [
            "expand by occasion, climate zone, and profession-specific needs",
            "add richer fit ontology including rise, cut, and mobility traits",
            "deepen sustainability and lifecycle care metadata",
        ],
    },
    {
        "mega_category_id": "footwear_shoes_sneakers_boots",
        "engine_id": "fashion_footwear_jewelry_accessories_engine",
        "display_name": "Footwear / Shoes / Sneakers / Boots",
        "coverage_status": "needs_deep_expansion",
        "coverage_depth_target": "deep_vertical_pack_v1",
        "department_seed_examples": [
            "everyday casual footwear",
            "running and training footwear",
            "hiking and trail footwear",
            "formal and office footwear",
            "protective and work boots",
            "kids and family footwear",
            "comfort and orthotic-compatible footwear",
        ],
        "subcategory_seed_examples": [
            "low-top and high-top sneakers",
            "road running shoes",
            "trail running shoes",
            "basketball and court shoes",
            "leather office shoes",
            "ankle and knee-high boots",
            "steel-toe safety boots",
            "waterproof hiking boots",
            "sandals and summer slip-ons",
            "kids school shoes",
            "wide-fit comfort shoes",
            "winter traction footwear",
        ],
        "product_family_seed_examples": [
            "daily comfort sneaker lines",
            "max-cushion running families",
            "stability running platforms",
            "all-terrain hiking boot ranges",
            "premium leather loafer lines",
            "anti-slip safety boot families",
            "waterproof trail shoe ranges",
            "kids growth-fit shoe families",
            "orthotic-ready footwear lines",
            "insulated winter boot systems",
        ],
        "spec_schema_seed_examples": [
            "size_system",
            "fit_width",
            "upper_material",
            "midsole_type",
            "outsole_traction_profile",
            "heel_drop_mm",
            "waterproofing_support",
            "safety_toe_standard",
            "intended_surface_type",
        ],
        "buying_priority_seed_examples": [
            "fit_accuracy",
            "all-day_comfort",
            "activity_specific_support",
            "grip_and_stability",
            "weather_protection",
            "durability_for_frequency_of_use",
            "workplace_compliance_when_required",
        ],
        "alias_seed_examples": [
            "shoes",
            "sneakers",
            "boots",
            "performance footwear",
            "work safety shoes",
            "everyday trainers",
        ],
        "greeklish_seed_examples": [
            "papoutsia treksimo",
            "sneakers kathimerina",
            "mpotes oreivasias",
            "papoutsia asfaleias",
            "papoutsia grafeiou",
            "orthopedic style papoutsia",
        ],
        "typo_seed_examples": [
            "papoutsa treximo",
            "snakers",
            "mpotes oreibasias",
            "asfalias papoutsia",
            "grafiou papoutsia",
            "ortho pedic papoutsia",
        ],
        "intent_pattern_seed_examples": [
            "pick one footwear rotation for work gym and weekends",
            "compare cushioning and support for long walking days",
            "select protective boots for demanding job environments",
            "match shoe grip to weather and surface needs",
            "balance style and comfort in formal footwear",
        ],
        "ambiguity_risks": [
            "boot terms overlap with moto and safety categories",
            "trainer terms may refer to fitness equipment or shoes",
            "comfort shoe queries can overlap with health support products",
        ],
        "safety_notes": [
            "avoid medical correction claims from footwear",
            "do not claim guaranteed slip prevention outcomes",
            "state that protective compliance depends on certified standards",
        ],
        "future_expansion_notes": [
            "expand by gait profile, terrain, and wear frequency",
            "add fit recommendation dimensions beyond size and width",
            "deepen lifecycle replacement signals for performance footwear",
        ],
    },
    {
        "mega_category_id": "jewelry_watches_bags_fashion_accessories",
        "engine_id": "fashion_footwear_jewelry_accessories_engine",
        "display_name": "Jewelry / Watches / Bags / Fashion Accessories",
        "coverage_status": "needs_deep_expansion",
        "coverage_depth_target": "deep_vertical_pack_v1",
        "department_seed_examples": [
            "jewelry collections",
            "watch and timepiece systems",
            "bags and carry solutions",
            "small leather goods",
            "eyewear and fashion accents",
            "occasion and gifting accessories",
            "travel and utility accessories",
        ],
        "subcategory_seed_examples": [
            "rings necklaces bracelets earrings",
            "smart and analog watches",
            "crossbody tote and backpack bags",
            "wallets cardholders and organizers",
            "belts scarves hats and gloves",
            "sunglasses and optical fashion frames",
            "occasion clutches and evening bags",
            "travel organizers and garment accessories",
            "jewelry storage and care accessories",
            "watch straps and maintenance accessories",
            "fashion gift-set bundles",
        ],
        "product_family_seed_examples": [
            "minimal jewelry line families",
            "statement accessory collections",
            "sport and lifestyle watch ranges",
            "business carry bag platforms",
            "anti-theft urban backpack lines",
            "premium wallet family ranges",
            "seasonal scarf and glove collections",
            "polarized eyewear families",
            "occasion clutch product lines",
            "watch strap ecosystem ranges",
        ],
        "spec_schema_seed_examples": [
            "material_type",
            "finish_color",
            "dimension_profile",
            "strap_or_chain_length",
            "water_resistance_for_watches",
            "compartment_layout",
            "closure_type",
            "style_occasion_tags",
            "care_requirements",
        ],
        "buying_priority_seed_examples": [
            "style_coordination",
            "daily_utility",
            "material_durability",
            "occasion_readiness",
            "carry_capacity_when_relevant",
            "comfort_and_wearability",
            "long-term_maintenance",
        ],
        "alias_seed_examples": [
            "fashion accessories",
            "bags and jewelry",
            "watch collections",
            "style add-ons",
            "carry accessories",
            "outfit finishing pieces",
        ],
        "greeklish_seed_examples": [
            "tsanta omou kathimerini",
            "rologi antriko",
            "kosmimata minimal",
            "gualia iliou",
            "portofoli kartothiki",
            "aksesouar exodou",
        ],
        "typo_seed_examples": [
            "tsanda omou",
            "roloi antriko",
            "kosimata miniml",
            "gialia ilioy",
            "portofoli",
            "aksesuar exodou",
        ],
        "intent_pattern_seed_examples": [
            "build complete accessory layer for wardrobe",
            "match bag capacity with daily commuting needs",
            "select watch style for work and occasion crossover",
            "compare durable materials for frequent use",
            "coordinate jewelry and eyewear with seasonal outfits",
        ],
        "ambiguity_risks": [
            "watch term overlaps with smart wearables in mobile category",
            "carry accessories overlap with travel and outdoor gear",
            "care accessories overlap with beauty personal care items",
        ],
        "safety_notes": [
            "avoid authenticity or valuation claims beyond provided metadata",
            "do not imply medical eye-protection claims for fashion eyewear",
            "mark that material sensitivities vary by user",
        ],
        "future_expansion_notes": [
            "expand by style archetype and occasion graph",
            "add material and finish compatibility ontology",
            "deepen accessory-bundle suggestions across apparel and footwear",
        ],
    },
]


def get_mega_category_coverage_plan() -> list[dict]:
    """Return deterministic deep-taxonomy expansion blueprint records."""
    return deepcopy(_MEGA_CATEGORY_COVERAGE_PLAN)


def get_coverage_plan_for_mega_category(mega_category_id: str) -> dict | None:
    """Return one mega-category coverage blueprint record by identifier."""
    for record in _MEGA_CATEGORY_COVERAGE_PLAN:
        if record["mega_category_id"] == mega_category_id:
            return deepcopy(record)
    return None


def summarize_coverage_plan() -> dict:
    """Return deterministic aggregate counts for the coverage blueprint."""
    plan = get_mega_category_coverage_plan()
    status_counts = Counter(record["coverage_status"] for record in plan)
    engine_counts = Counter(record["engine_id"] for record in plan)

    return {
        "engine_count": len(engine_counts),
        "mega_category_count": len(plan),
        "engines_represented": sorted(engine_counts.keys()),
        "mega_categories_represented": [record["mega_category_id"] for record in plan],
        "coverage_status_counts": dict(sorted(status_counts.items())),
        "per_engine_mega_category_counts": dict(sorted(engine_counts.items())),
        "blueprint_only": True,
        "deep_taxonomy_completed": False,
        "local_nlu_deep_proof_scope": [
            "car_tyres",
            "calculators",
            "power_banks",
            "chargers",
            "ambiguous",
            "unknown",
        ],
    }


def _is_json_serializable(payload: object) -> bool:
    try:
        json.dumps(payload, sort_keys=True)
    except (TypeError, ValueError):
        return False
    return True


def _has_forbidden_fields(plan: list[dict]) -> bool:
    for record in plan:
        for key in record.keys():
            lowered = key.lower()
            if any(token in lowered for token in _FORBIDDEN_KEY_TOKENS):
                return True
    return False


def _has_required_shape(record: dict) -> bool:
    required_scalar_fields = (
        "mega_category_id",
        "engine_id",
        "display_name",
        "coverage_status",
        "coverage_depth_target",
    )
    if any(field not in record or not isinstance(record[field], str) for field in required_scalar_fields):
        return False
    if record["coverage_status"] not in _ALLOWED_COVERAGE_STATUSES:
        return False
    for field in _REQUIRED_LIST_FIELDS:
        value = record.get(field)
        if not isinstance(value, list) or not value:
            return False
    return True


def validate_coverage_plan() -> dict:
    """Validate deterministic structure and locked-architecture alignment."""
    plan = get_mega_category_coverage_plan()
    engines = get_engine_registry()
    mega_categories = get_mega_category_registry()
    valid_engine_ids = {engine["engine_id"] for engine in engines}
    valid_mega_ids = [record["mega_category_id"] for record in mega_categories]
    per_engine_counts = Counter(record["engine_id"] for record in plan)
    plan_mega_ids = [record["mega_category_id"] for record in plan]
    summary = summarize_coverage_plan()

    result = {
        "valid": True,
        "passed": True,
        "engine_count": len(per_engine_counts),
        "expected_engine_count": 6,
        "mega_category_count": len(plan),
        "expected_mega_category_count": 18,
        "all_engine_references_valid": all(record["engine_id"] in valid_engine_ids for record in plan),
        "all_mega_category_ids_valid": all(record["mega_category_id"] in set(valid_mega_ids) for record in plan),
        "all_records_have_required_shape": all(_has_required_shape(record) for record in plan),
        "exactly_three_mega_categories_per_engine": all(
            per_engine_counts.get(engine["engine_id"], 0) == 3 for engine in engines
        ),
        "deterministic_ordering": plan_mega_ids == valid_mega_ids,
        "forbidden_fields_present": _has_forbidden_fields(plan),
        "is_json_serializable": _is_json_serializable({"coverage_plan": plan, "summary": summary}),
        "coverage_status_counts": summary["coverage_status_counts"],
        "per_engine_mega_category_counts": dict(sorted(per_engine_counts.items())),
        "blueprint_only": summary["blueprint_only"],
        "deep_taxonomy_completed": summary["deep_taxonomy_completed"],
        "local_nlu_proof_is_limited": True,
        "no_claude_or_api_or_live_llm_required": True,
        "no_app_router_or_decision_machine_dependency_required": True,
    }
    result["valid"] = (
        result["engine_count"] == result["expected_engine_count"]
        and result["mega_category_count"] == result["expected_mega_category_count"]
        and result["all_engine_references_valid"]
        and result["all_mega_category_ids_valid"]
        and result["all_records_have_required_shape"]
        and result["exactly_three_mega_categories_per_engine"]
        and result["deterministic_ordering"]
        and not result["forbidden_fields_present"]
        and result["is_json_serializable"]
        and result["blueprint_only"]
        and not result["deep_taxonomy_completed"]
        and result["local_nlu_proof_is_limited"]
        and result["no_claude_or_api_or_live_llm_required"]
        and result["no_app_router_or_decision_machine_dependency_required"]
    )
    result["passed"] = result["valid"]
    return result
