from __future__ import annotations

from copy import deepcopy

_SCHEMA_VERSION = "1.0.0"
_SOURCE = "stage_22b_taxonomy_lock"
_STATUS = "active"

_MEGA_CATEGORY_REGISTRY = [
    {
        "mega_category_id": "home_appliances_laundry_climate",
        "engine_id": "home_living_appliances_engine",
        "display_name": "Home Appliances / Laundry / Climate",
        "description": "Major home systems for appliance ownership, climate control, and long-lifecycle household equipment.",
        "department_seed_examples": ["major appliances", "laundry systems", "climate control"],
        "intent_seed_examples": ["replace old appliance", "energy efficient upgrade", "compare capacity and reliability"],
        "status": _STATUS,
        "source": _SOURCE,
        "schema_version": _SCHEMA_VERSION,
    },
    {
        "mega_category_id": "kitchen_cooking_household",
        "engine_id": "home_living_appliances_engine",
        "display_name": "Kitchen / Cooking / Household",
        "description": "Kitchen and everyday household universe for preparation, cleaning, food workflows, and home routines.",
        "department_seed_examples": ["kitchen devices", "cookware and prep", "household care"],
        "intent_seed_examples": ["optimize meal prep", "save countertop space", "find easy-clean options"],
        "status": _STATUS,
        "source": _SOURCE,
        "schema_version": _SCHEMA_VERSION,
    },
    {
        "mega_category_id": "furniture_living_storage_smart_home",
        "engine_id": "home_living_appliances_engine",
        "display_name": "Furniture / Living / Storage / Smart Home",
        "description": "Living-space setup universe including furniture systems, organization, and connected home control.",
        "department_seed_examples": ["living furniture", "storage solutions", "smart home control"],
        "intent_seed_examples": ["maximize small space", "upgrade room comfort", "coordinate connected devices"],
        "status": _STATUS,
        "source": _SOURCE,
        "schema_version": _SCHEMA_VERSION,
    },
    {
        "mega_category_id": "phones_mobile_accessories",
        "engine_id": "tech_electronics_office_engine",
        "display_name": "Phones / Mobile / Accessories",
        "description": "Mobile communication universe covering phones, mobile ecosystems, and accessory compatibility.",
        "department_seed_examples": ["smartphones", "mobile wearables", "mobile accessories"],
        "intent_seed_examples": ["compare mobile performance", "improve battery workflow", "match compatible accessories"],
        "status": _STATUS,
        "source": _SOURCE,
        "schema_version": _SCHEMA_VERSION,
    },
    {
        "mega_category_id": "computers_office_peripherals",
        "engine_id": "tech_electronics_office_engine",
        "display_name": "Computers / Office / Peripherals",
        "description": "Work and productivity universe for computers, office hardware, peripherals, and workflow tooling.",
        "department_seed_examples": ["laptops and desktops", "office hardware", "input and display peripherals"],
        "intent_seed_examples": ["set up work-from-home", "balance performance and portability", "expand workstation"],
        "status": _STATUS,
        "source": _SOURCE,
        "schema_version": _SCHEMA_VERSION,
    },
    {
        "mega_category_id": "audio_video_gaming_cameras",
        "engine_id": "tech_electronics_office_engine",
        "display_name": "Audio / Video / Gaming / Cameras",
        "description": "Media and entertainment universe including sound, visual, gaming, and capture systems.",
        "department_seed_examples": ["audio systems", "home video displays", "gaming and camera gear"],
        "intent_seed_examples": ["upgrade media quality", "build gaming setup", "capture content clearly"],
        "status": _STATUS,
        "source": _SOURCE,
        "schema_version": _SCHEMA_VERSION,
    },
    {
        "mega_category_id": "car_parts_service_maintenance",
        "engine_id": "auto_moto_mobility_engine",
        "display_name": "Car Parts / Service / Maintenance",
        "description": "Automotive upkeep universe for parts replacement, scheduled service, and reliability maintenance.",
        "department_seed_examples": ["engine and braking parts", "service consumables", "maintenance tools"],
        "intent_seed_examples": ["restore vehicle reliability", "schedule routine upkeep", "find fitment-safe parts"],
        "status": _STATUS,
        "source": _SOURCE,
        "schema_version": _SCHEMA_VERSION,
    },
    {
        "mega_category_id": "tyres_wheels_car_accessories",
        "engine_id": "auto_moto_mobility_engine",
        "display_name": "Tyres / Wheels / Car Accessories",
        "description": "Road-contact and vehicle enhancement universe for tyre fitment, wheel systems, and accessories.",
        "department_seed_examples": ["seasonal tyres", "wheel options", "interior and exterior accessories"],
        "intent_seed_examples": ["improve road grip", "match wheel sizing", "enhance vehicle convenience"],
        "status": _STATUS,
        "source": _SOURCE,
        "schema_version": _SCHEMA_VERSION,
    },
    {
        "mega_category_id": "moto_bicycle_mobility_gear",
        "engine_id": "auto_moto_mobility_engine",
        "display_name": "Moto / Bicycle / Mobility Gear",
        "description": "Two-wheel and personal mobility universe for riding systems, components, and safety gear.",
        "department_seed_examples": ["motorcycle gear", "bicycle components", "mobility equipment"],
        "intent_seed_examples": ["commute more efficiently", "improve rider safety", "upgrade ride durability"],
        "status": _STATUS,
        "source": _SOURCE,
        "schema_version": _SCHEMA_VERSION,
    },
    {
        "mega_category_id": "power_tools_workshop",
        "engine_id": "tools_diy_garden_repair_engine",
        "display_name": "Power Tools / Workshop",
        "description": "Core build-and-repair universe for powered tools, workshop machines, and project execution.",
        "department_seed_examples": ["drilling and cutting", "workshop machines", "tool power systems"],
        "intent_seed_examples": ["speed up project work", "improve cut precision", "choose durable workshop setup"],
        "status": _STATUS,
        "source": _SOURCE,
        "schema_version": _SCHEMA_VERSION,
    },
    {
        "mega_category_id": "hand_tools_consumables_measuring",
        "engine_id": "tools_diy_garden_repair_engine",
        "display_name": "Hand Tools / Consumables / Measuring",
        "description": "Foundational repair universe for manual tools, fasteners, abrasives, and measurement control.",
        "department_seed_examples": ["hand tools", "consumables and fixings", "measurement instruments"],
        "intent_seed_examples": ["complete precision repairs", "restock workshop essentials", "improve fitting accuracy"],
        "status": _STATUS,
        "source": _SOURCE,
        "schema_version": _SCHEMA_VERSION,
    },
    {
        "mega_category_id": "garden_outdoor_repair_building",
        "engine_id": "tools_diy_garden_repair_engine",
        "display_name": "Garden / Outdoor / Repair / Building",
        "description": "Property and outdoor universe for gardening, exterior upkeep, and structural repair/build tasks.",
        "department_seed_examples": ["garden maintenance", "outdoor equipment", "building and repair supplies"],
        "intent_seed_examples": ["maintain outdoor spaces", "handle seasonal repairs", "plan durable build projects"],
        "status": _STATUS,
        "source": _SOURCE,
        "schema_version": _SCHEMA_VERSION,
    },
    {
        "mega_category_id": "health_wellness_safety_devices",
        "engine_id": "health_beauty_family_lifestyle_engine",
        "display_name": "Health / Wellness / Safety Devices",
        "description": "Personal wellbeing universe for preventive health, wellness monitoring, and safety support devices.",
        "department_seed_examples": ["wellness monitoring", "health support devices", "personal safety devices"],
        "intent_seed_examples": ["track wellbeing metrics", "support daily health routines", "improve household safety"],
        "status": _STATUS,
        "source": _SOURCE,
        "schema_version": _SCHEMA_VERSION,
    },
    {
        "mega_category_id": "beauty_grooming_personal_care",
        "engine_id": "health_beauty_family_lifestyle_engine",
        "display_name": "Beauty / Grooming / Personal Care",
        "description": "Routine care universe for skin, hair, grooming, and long-term personal care outcomes.",
        "department_seed_examples": ["skincare routines", "hair and grooming", "personal care essentials"],
        "intent_seed_examples": ["improve care consistency", "choose skin-compatible products", "build grooming kit"],
        "status": _STATUS,
        "source": _SOURCE,
        "schema_version": _SCHEMA_VERSION,
    },
    {
        "mega_category_id": "baby_kids_pets_sports_outdoor",
        "engine_id": "health_beauty_family_lifestyle_engine",
        "display_name": "Baby / Kids / Pets / Sports / Outdoor",
        "description": "Family lifestyle universe spanning childcare, pets, active recreation, and outdoor daily life.",
        "department_seed_examples": ["baby and kids care", "pet support", "sports and outdoor essentials"],
        "intent_seed_examples": ["support family routines", "equip active lifestyle", "balance comfort and durability"],
        "status": _STATUS,
        "source": _SOURCE,
        "schema_version": _SCHEMA_VERSION,
    },
    {
        "mega_category_id": "clothing_apparel_workwear",
        "engine_id": "fashion_footwear_jewelry_accessories_engine",
        "display_name": "Clothing / Apparel / Workwear",
        "description": "Dedicated fashion universe for clothing systems across style, seasonal use, and professional wear.",
        "department_seed_examples": ["everyday apparel", "seasonal clothing", "workwear"],
        "intent_seed_examples": ["build versatile wardrobe", "match fit and function", "compare fabric and durability"],
        "status": _STATUS,
        "source": _SOURCE,
        "schema_version": _SCHEMA_VERSION,
    },
    {
        "mega_category_id": "footwear_shoes_sneakers_boots",
        "engine_id": "fashion_footwear_jewelry_accessories_engine",
        "display_name": "Footwear / Shoes / Sneakers / Boots",
        "description": "Dedicated footwear universe for activity-specific shoes, fit comfort, and long-wear performance.",
        "department_seed_examples": ["casual shoes", "athletic footwear", "boots and protective footwear"],
        "intent_seed_examples": ["optimize daily comfort", "choose activity-specific footwear", "compare support and grip"],
        "status": _STATUS,
        "source": _SOURCE,
        "schema_version": _SCHEMA_VERSION,
    },
    {
        "mega_category_id": "jewelry_watches_bags_fashion_accessories",
        "engine_id": "fashion_footwear_jewelry_accessories_engine",
        "display_name": "Jewelry / Watches / Bags / Fashion Accessories",
        "description": "Dedicated accessories universe for adornment, utility carry, and coordinated personal style systems.",
        "department_seed_examples": ["jewelry and watches", "bags and carry", "style accessories"],
        "intent_seed_examples": ["coordinate complete outfit", "select occasion-ready accessories", "balance style and utility"],
        "status": _STATUS,
        "source": _SOURCE,
        "schema_version": _SCHEMA_VERSION,
    },
]


def get_mega_category_registry() -> list[dict]:
    """Return a deep-copied deterministic mega-category registry."""
    return deepcopy(_MEGA_CATEGORY_REGISTRY)
